// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication9.Models;

namespace WebApplication9.Migrations
{
    [DbContext(typeof(EscuelitaTablas))]
    partial class EscuelitaTablasModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication9.Models.Alumnos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Alumnos");
                });

            modelBuilder.Entity("WebApplication9.Models.Cursos", b =>
                {
                    b.Property<int>("idCursos")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre");

                    b.HasKey("idCursos");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("WebApplication9.Models.EstudiantesCursos", b =>
                {
                    b.Property<int>("IdCursos");

                    b.Property<int>("idEstudiante");

                    b.HasKey("IdCursos", "idEstudiante");

                    b.HasIndex("idEstudiante");

                    b.ToTable("estudiantesCursos");
                });

            modelBuilder.Entity("WebApplication9.Models.Profesores", b =>
                {
                    b.Property<int>("idProfesores")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre");

                    b.Property<int>("idCursos");

                    b.HasKey("idProfesores");

                    b.HasIndex("idCursos")
                        .IsUnique();

                    b.ToTable("Profesores");
                });

            modelBuilder.Entity("WebApplication9.Models.EstudiantesCursos", b =>
                {
                    b.HasOne("WebApplication9.Models.Cursos", "Cursos")
                        .WithMany("Alumnos")
                        .HasForeignKey("IdCursos")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebApplication9.Models.Alumnos", "Alumno")
                        .WithMany("Cursos")
                        .HasForeignKey("idEstudiante")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebApplication9.Models.Profesores", b =>
                {
                    b.HasOne("WebApplication9.Models.Cursos", "Curso")
                        .WithOne("profesores")
                        .HasForeignKey("WebApplication9.Models.Profesores", "idCursos")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
